//
//  TriMode59cellTonnetzMac.swift
//  Tonnetz
//
//  Created by Thom Jordan on 8/9/19.
//  Copyright © 2019 RatioExemplar. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



import Cocoa

public class TriMode59cellTonnetzMac : NSObject {

    //// Drawing Methods

    @objc dynamic public class func drawCellSym(frame targetFrame: NSRect = NSRect(x: 0, y: 0, width: 175, height: 203), resizing: ResizingBehavior = .aspectFit, color: CGFloat = 0, colorOS: CGFloat = 4, pcOS: CGFloat = 0, rowOS: CGFloat = 0, mode: CGFloat = 0) {
        //// General Declarations
        let context = NSGraphicsContext.current!.cgContext
        
        //// Resize to Target Frame
        NSGraphicsContext.saveGraphicsState()
        let resizedFrame: NSRect = resizing.apply(rect: NSRect(x: 0, y: 0, width: 175, height: 203), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 175, y: resizedFrame.height / 203)


        //// Color Declarations
        let grey = NSColor(red: 0.502, green: 0.502, blue: 0.502, alpha: 0.96)
        let liteGrey = NSColor(red: 0.79, green: 0.79, blue: 0.79, alpha: 0.97)
        let red = NSColor(red: 1, green: 0, blue: 0, alpha: 1)
        let orange = NSColor(red: 1, green: 0.502, blue: 0, alpha: 1)
        let yellow = NSColor(red: 1, green: 1, blue: 0, alpha: 1)
        let yellowGreen = NSColor(red: 0.502, green: 1, blue: 0, alpha: 1)
        let green = NSColor(red: 0, green: 1, blue: 0, alpha: 1)
        let greenBlue = NSColor(red: 0, green: 1, blue: 0.502, alpha: 1)
        let blueGreen = NSColor(red: 0, green: 1, blue: 1, alpha: 1)
        let blue = NSColor(red: 0, green: 0.502, blue: 1, alpha: 1)
        let indigo = NSColor(red: 0, green: 0, blue: 1, alpha: 1)
        let violet = NSColor(red: 0.502, green: 0, blue: 1, alpha: 1)
        let purple = NSColor(red: 1, green: 0, blue: 1, alpha: 1)
        let magenta = NSColor(red: 1, green: 0, blue: 0.502, alpha: 1)
        let charcoal = NSColor(red: 0.216, green: 0.216, blue: 0.216, alpha: 1)

        //// Variable Declarations
        let colE: CGFloat = fmod(color, 12) == 0 ? 0 : (fmod(color, 12) == 1 ? 7 : (fmod(color, 12) == 2 ? 2 : (fmod(color, 12) == 3 ? 9 : (fmod(color, 12) == 4 ? 4 : (fmod(color, 12) == 5 ? 11 : (fmod(color, 12) == 6 ? 6 : (fmod(color, 12) == 7 ? 1 : (fmod(color, 12) == 8 ? 8 : (fmod(color, 12) == 9 ? 3 : (fmod(color, 12) == 10 ? 10 : 5))))))))))
        let pcOSe: CGFloat = fmod(pcOS, 12) == 0 ? 0 : (fmod(pcOS, 12) == 1 ? 7 : (fmod(pcOS, 12) == 2 ? 2 : (fmod(pcOS, 12) == 3 ? 9 : (fmod(pcOS, 12) == 4 ? 4 : (fmod(pcOS, 12) == 5 ? 11 : (fmod(pcOS, 12) == 6 ? 6 : (fmod(pcOS, 12) == 7 ? 1 : (fmod(pcOS, 12) == 8 ? 8 : (fmod(pcOS, 12) == 9 ? 3 : (fmod(pcOS, 12) == 10 ? 10 : 5))))))))))
        let rowOSe: CGFloat = fmod(rowOS, 12) == 0 ? 0 : (fmod(rowOS, 12) == 1 ? 7 : (fmod(rowOS, 12) == 2 ? 2 : (fmod(rowOS, 12) == 3 ? 9 : (fmod(rowOS, 12) == 4 ? 4 : (fmod(rowOS, 12) == 5 ? 11 : (fmod(rowOS, 12) == 6 ? 6 : (fmod(rowOS, 12) == 7 ? 1 : (fmod(rowOS, 12) == 8 ? 8 : (fmod(rowOS, 12) == 9 ? 3 : (fmod(rowOS, 12) == 10 ? 10 : 5))))))))))
        let colorExp: NSColor = fmod((colE + pcOSe + rowOSe + colorOS), 12) == 0 ? red : (fmod((colE + pcOSe + rowOSe + colorOS), 12) == 1 ? orange : (fmod((colE + pcOSe + rowOSe + colorOS), 12) == 2 ? yellow : (fmod((colE + pcOSe + rowOSe + colorOS), 12) == 3 ? yellowGreen : (fmod((colE + pcOSe + rowOSe + colorOS), 12) == 4 ? green : (fmod((colE + pcOSe + rowOSe + colorOS), 12) == 5 ? greenBlue : (fmod((colE + pcOSe + rowOSe + colorOS), 12) == 6 ? blueGreen : (fmod((colE + pcOSe + rowOSe + colorOS), 12) == 7 ? blue : (fmod((colE + pcOSe + rowOSe + colorOS), 12) == 8 ? indigo : (fmod((colE + pcOSe + rowOSe + colorOS), 12) == 9 ? violet : (fmod((colE + pcOSe + rowOSe + colorOS), 12) == 10 ? purple : magenta))))))))))
        let noteCalc: String = fmod((pcOSe + colE + rowOSe), 12) == 0 ? "C" : (fmod((pcOSe + colE + rowOSe), 12) == 1 ? "G" : (fmod((pcOSe + colE + rowOSe), 12) == 2 ? "D" : (fmod((pcOSe + colE + rowOSe), 12) == 3 ? "A" : (fmod((pcOSe + colE + rowOSe), 12) == 4 ? "E" : (fmod((pcOSe + colE + rowOSe), 12) == 5 ? "B" : (fmod((pcOSe + colE + rowOSe), 12) == 6 ? "F#" : (fmod((pcOSe + colE + rowOSe), 12) == 7 ? "Db" : (fmod((pcOSe + colE + rowOSe), 12) == 8 ? "Ab" : (fmod((pcOSe + colE + rowOSe), 12) == 9 ? "Eb" : (fmod((pcOSe + colE + rowOSe), 12) == 10 ? "Bb" : "F"))))))))))
        let isMode0: Bool = fmod(mode, 3) == 0
        let isMode2: Bool = fmod(mode, 3) == 2

        //// pA Drawing
        let pAPath = NSBezierPath()
        pAPath.move(to: NSPoint(x: 88, y: 202))
        pAPath.line(to: NSPoint(x: 174.6, y: 152))
        pAPath.line(to: NSPoint(x: 174.6, y: 52))
        pAPath.line(to: NSPoint(x: 88, y: 2))
        pAPath.line(to: NSPoint(x: 1.4, y: 52))
        pAPath.line(to: NSPoint(x: 1.4, y: 152))
        pAPath.close()
        colorExp.setFill()
        pAPath.fill()
        charcoal.setStroke()
        pAPath.lineWidth = 3
        pAPath.stroke()


        if (isMode0) {
            //// pB Drawing
            let pBPath = NSBezierPath()
            pBPath.move(to: NSPoint(x: 88, y: 202))
            pBPath.line(to: NSPoint(x: 174.6, y: 152))
            pBPath.line(to: NSPoint(x: 174.6, y: 52))
            pBPath.line(to: NSPoint(x: 88, y: 2))
            pBPath.line(to: NSPoint(x: 1.4, y: 52))
            pBPath.line(to: NSPoint(x: 1.4, y: 152))
            pBPath.close()
            grey.setFill()
            pBPath.fill()
            NSColor.darkGray.setStroke()
            pBPath.lineWidth = 1.5
            pBPath.stroke()
        }


        if (isMode2) {
            //// pC Drawing
            let pCPath = NSBezierPath()
            pCPath.move(to: NSPoint(x: 88, y: 202))
            pCPath.line(to: NSPoint(x: 174.6, y: 152))
            pCPath.line(to: NSPoint(x: 174.6, y: 52))
            pCPath.line(to: NSPoint(x: 88, y: 2))
            pCPath.line(to: NSPoint(x: 1.4, y: 52))
            pCPath.line(to: NSPoint(x: 1.4, y: 152))
            pCPath.close()
            liteGrey.setFill()
            pCPath.fill()
            NSColor.darkGray.setStroke()
            pCPath.lineWidth = 1.5
            pCPath.stroke()
        }


        //// pTB Drawing
        NSGraphicsContext.saveGraphicsState()
        context.setAlpha(0.1)
        context.setBlendMode(.multiply)

        let pTBPath = NSBezierPath(roundedRect: NSRect(x: 60.5, y: 75.5, width: 55, height: 55), xRadius: 27.5, yRadius: 27.5)
        NSColor.gray.setFill()
        pTBPath.fill()

        NSGraphicsContext.restoreGraphicsState()


        //// pT Drawing
        let pTRect = NSRect(x: 65, y: 85.5, width: 45, height: 37.5)
        let pTStyle = NSMutableParagraphStyle()
        pTStyle.alignment = .center
        let pTFontAttributes = [
            .font: NSFont.systemFont(ofSize: 34, weight: .semibold),
            .foregroundColor: NSColor.white,
            .paragraphStyle: pTStyle,
        ] as [NSAttributedString.Key: Any]

        let pTTextHeight: CGFloat = noteCalc.boundingRect(with: NSSize(width: pTRect.width, height: CGFloat.infinity), options: .usesLineFragmentOrigin, attributes: pTFontAttributes).height
        let pTTextRect: NSRect = NSRect(x: pTRect.minX, y: pTRect.minY + (pTRect.height - pTTextHeight) / 2, width: pTRect.width, height: pTTextHeight)
        NSGraphicsContext.saveGraphicsState()
        pTRect.clip()
        noteCalc.draw(in: pTTextRect.offsetBy(dx: 0, dy: 0), withAttributes: pTFontAttributes)
        NSGraphicsContext.restoreGraphicsState()
        
        NSGraphicsContext.restoreGraphicsState()

    }

    @objc dynamic public class func drawTonnetz(colorOS: CGFloat = 4, pcOS: CGFloat = 0, mode1: CGFloat = 0, mode2: CGFloat = 0, mode3: CGFloat = 0, mode4: CGFloat = 0, mode5: CGFloat = 0, mode6: CGFloat = 0, mode7: CGFloat = 0, mode8: CGFloat = 0, mode9: CGFloat = 0, mode10: CGFloat = 0, mode11: CGFloat = 0, mode12: CGFloat = 0, mode13: CGFloat = 0, mode14: CGFloat = 0, mode15: CGFloat = 0, mode16: CGFloat = 0, mode17: CGFloat = 0, mode18: CGFloat = 0, mode19: CGFloat = 0, mode20: CGFloat = 0, mode21: CGFloat = 0, mode22: CGFloat = 0, mode23: CGFloat = 0, mode24: CGFloat = 0, mode25: CGFloat = 0, mode26: CGFloat = 0, mode27: CGFloat = 0, mode28: CGFloat = 0, mode29: CGFloat = 0, mode30: CGFloat = 0, mode31: CGFloat = 0, mode32: CGFloat = 0, mode33: CGFloat = 0, mode34: CGFloat = 0, mode35: CGFloat = 0, mode36: CGFloat = 0, mode37: CGFloat = 0, mode38: CGFloat = 0, mode39: CGFloat = 0, mode40: CGFloat = 0, mode41: CGFloat = 0, mode42: CGFloat = 0, mode43: CGFloat = 0, mode44: CGFloat = 0, mode45: CGFloat = 0, mode46: CGFloat = 0, mode47: CGFloat = 0, mode48: CGFloat = 0, mode49: CGFloat = 0, mode50: CGFloat = 0, mode51: CGFloat = 0, mode52: CGFloat = 0, mode53: CGFloat = 0, mode54: CGFloat = 0, mode55: CGFloat = 0, mode56: CGFloat = 0, mode57: CGFloat = 0, mode58: CGFloat = 0, mode59: CGFloat = 0) {
        //// General Declarations
        let context = NSGraphicsContext.current!.cgContext


        //// Variable Declarations
        let pcOSadjusted: CGFloat = pcOS + 1
        let c0: CGFloat = 0
        let c1: CGFloat = 1
        let c2: CGFloat = 2
        let c4: CGFloat = 4
        let c6: CGFloat = 6
        let c7: CGFloat = 7
        let c8: CGFloat = 8
        let c9: CGFloat = 9
        let c10: CGFloat = 10
        let c11: CGFloat = 11

        //// Group
        //// Cell 1 Drawing
        let cell1Rect = NSRect(x: 66, y: 618, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell1Rect.clip()
        context.translateBy(x: cell1Rect.minX, y: cell1Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell1Rect.size), resizing: .stretch, color: c0, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c0, mode: mode1)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 2 Drawing
        let cell2Rect = NSRect(x: 178, y: 618, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell2Rect.clip()
        context.translateBy(x: cell2Rect.minX, y: cell2Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell2Rect.size), resizing: .stretch, color: c7, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c0, mode: mode2)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 3 Drawing
        let cell3Rect = NSRect(x: 290, y: 618, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell3Rect.clip()
        context.translateBy(x: cell3Rect.minX, y: cell3Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell3Rect.size), resizing: .stretch, color: c2, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c0, mode: mode3)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 4 Drawing
        let cell4Rect = NSRect(x: 402, y: 618, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell4Rect.clip()
        context.translateBy(x: cell4Rect.minX, y: cell4Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell4Rect.size), resizing: .stretch, color: c9, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c0, mode: mode4)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 5 Drawing
        let cell5Rect = NSRect(x: 514, y: 618, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell5Rect.clip()
        context.translateBy(x: cell5Rect.minX, y: cell5Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell5Rect.size), resizing: .stretch, color: c4, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c0, mode: mode5)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 6 Drawing
        let cell6Rect = NSRect(x: 626, y: 618, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell6Rect.clip()
        context.translateBy(x: cell6Rect.minX, y: cell6Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell6Rect.size), resizing: .stretch, color: c11, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c0, mode: mode6)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 7 Drawing
        let cell7Rect = NSRect(x: 738, y: 618, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell7Rect.clip()
        context.translateBy(x: cell7Rect.minX, y: cell7Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell7Rect.size), resizing: .stretch, color: c6, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c0, mode: mode7)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 8 Drawing
        let cell8Rect = NSRect(x: 850, y: 618, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell8Rect.clip()
        context.translateBy(x: cell8Rect.minX, y: cell8Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell8Rect.size), resizing: .stretch, color: c1, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c0, mode: mode8)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 9 Drawing
        let cell9Rect = NSRect(x: 10, y: 520, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell9Rect.clip()
        context.translateBy(x: cell9Rect.minX, y: cell9Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell9Rect.size), resizing: .stretch, color: c0, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c8, mode: mode9)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 10 Drawing
        let cell10Rect = NSRect(x: 122, y: 520, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell10Rect.clip()
        context.translateBy(x: cell10Rect.minX, y: cell10Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell10Rect.size), resizing: .stretch, color: c7, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c8, mode: mode10)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 11 Drawing
        let cell11Rect = NSRect(x: 234, y: 520, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell11Rect.clip()
        context.translateBy(x: cell11Rect.minX, y: cell11Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell11Rect.size), resizing: .stretch, color: c2, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c8, mode: mode11)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 12 Drawing
        let cell12Rect = NSRect(x: 346, y: 520, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell12Rect.clip()
        context.translateBy(x: cell12Rect.minX, y: cell12Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell12Rect.size), resizing: .stretch, color: c9, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c8, mode: mode12)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 13 Drawing
        let cell13Rect = NSRect(x: 458, y: 520, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell13Rect.clip()
        context.translateBy(x: cell13Rect.minX, y: cell13Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell13Rect.size), resizing: .stretch, color: c4, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c8, mode: mode13)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 14 Drawing
        let cell14Rect = NSRect(x: 570, y: 520, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell14Rect.clip()
        context.translateBy(x: cell14Rect.minX, y: cell14Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell14Rect.size), resizing: .stretch, color: c11, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c8, mode: mode14)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 15 Drawing
        let cell15Rect = NSRect(x: 682, y: 520, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell15Rect.clip()
        context.translateBy(x: cell15Rect.minX, y: cell15Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell15Rect.size), resizing: .stretch, color: c6, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c8, mode: mode15)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 16 Drawing
        let cell16Rect = NSRect(x: 794, y: 520, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell16Rect.clip()
        context.translateBy(x: cell16Rect.minX, y: cell16Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell16Rect.size), resizing: .stretch, color: c1, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c8, mode: mode16)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 17 Drawing
        let cell17Rect = NSRect(x: 906, y: 520, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell17Rect.clip()
        context.translateBy(x: cell17Rect.minX, y: cell17Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell17Rect.size), resizing: .stretch, color: c8, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c8, mode: mode17)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 18 Drawing
        let cell18Rect = NSRect(x: 66, y: 422, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell18Rect.clip()
        context.translateBy(x: cell18Rect.minX, y: cell18Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell18Rect.size), resizing: .stretch, color: c0, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c11, mode: mode18)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 19 Drawing
        let cell19Rect = NSRect(x: 178, y: 422, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell19Rect.clip()
        context.translateBy(x: cell19Rect.minX, y: cell19Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell19Rect.size), resizing: .stretch, color: c7, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c11, mode: mode19)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 20 Drawing
        let cell20Rect = NSRect(x: 290, y: 422, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell20Rect.clip()
        context.translateBy(x: cell20Rect.minX, y: cell20Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell20Rect.size), resizing: .stretch, color: c2, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c11, mode: mode20)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 21 Drawing
        let cell21Rect = NSRect(x: 402, y: 422, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell21Rect.clip()
        context.translateBy(x: cell21Rect.minX, y: cell21Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell21Rect.size), resizing: .stretch, color: c9, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c11, mode: mode21)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 22 Drawing
        let cell22Rect = NSRect(x: 514, y: 422, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell22Rect.clip()
        context.translateBy(x: cell22Rect.minX, y: cell22Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell22Rect.size), resizing: .stretch, color: c4, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c11, mode: mode22)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 23 Drawing
        let cell23Rect = NSRect(x: 626, y: 422, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell23Rect.clip()
        context.translateBy(x: cell23Rect.minX, y: cell23Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell23Rect.size), resizing: .stretch, color: c11, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c11, mode: mode23)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 24 Drawing
        let cell24Rect = NSRect(x: 738, y: 422, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell24Rect.clip()
        context.translateBy(x: cell24Rect.minX, y: cell24Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell24Rect.size), resizing: .stretch, color: c6, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c11, mode: mode24)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 25 Drawing
        let cell25Rect = NSRect(x: 850, y: 422, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell25Rect.clip()
        context.translateBy(x: cell25Rect.minX, y: cell25Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell25Rect.size), resizing: .stretch, color: c1, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c11, mode: mode25)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 26 Drawing
        let cell26Rect = NSRect(x: 10, y: 324, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell26Rect.clip()
        context.translateBy(x: cell26Rect.minX, y: cell26Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell26Rect.size), resizing: .stretch, color: c0, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c7, mode: mode26)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 27 Drawing
        let cell27Rect = NSRect(x: 122, y: 324, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell27Rect.clip()
        context.translateBy(x: cell27Rect.minX, y: cell27Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell27Rect.size), resizing: .stretch, color: c7, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c7, mode: mode27)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 28 Drawing
        let cell28Rect = NSRect(x: 234, y: 324, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell28Rect.clip()
        context.translateBy(x: cell28Rect.minX, y: cell28Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell28Rect.size), resizing: .stretch, color: c2, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c7, mode: mode28)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 29 Drawing
        let cell29Rect = NSRect(x: 346, y: 324, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell29Rect.clip()
        context.translateBy(x: cell29Rect.minX, y: cell29Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell29Rect.size), resizing: .stretch, color: c9, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c7, mode: mode29)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 30 Drawing
        let cell30Rect = NSRect(x: 458, y: 324, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell30Rect.clip()
        context.translateBy(x: cell30Rect.minX, y: cell30Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell30Rect.size), resizing: .stretch, color: c4, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c7, mode: mode30)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 31 Drawing
        let cell31Rect = NSRect(x: 570, y: 324, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell31Rect.clip()
        context.translateBy(x: cell31Rect.minX, y: cell31Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell31Rect.size), resizing: .stretch, color: c11, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c7, mode: mode31)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 32 Drawing
        let cell32Rect = NSRect(x: 682, y: 324, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell32Rect.clip()
        context.translateBy(x: cell32Rect.minX, y: cell32Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell32Rect.size), resizing: .stretch, color: c6, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c7, mode: mode32)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 33 Drawing
        let cell33Rect = NSRect(x: 794, y: 324, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell33Rect.clip()
        context.translateBy(x: cell33Rect.minX, y: cell33Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell33Rect.size), resizing: .stretch, color: c1, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c7, mode: mode33)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 34 Drawing
        let cell34Rect = NSRect(x: 906, y: 324, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell34Rect.clip()
        context.translateBy(x: cell34Rect.minX, y: cell34Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell34Rect.size), resizing: .stretch, color: c8, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c7, mode: mode34)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 35 Drawing
        let cell35Rect = NSRect(x: 66, y: 226, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell35Rect.clip()
        context.translateBy(x: cell35Rect.minX, y: cell35Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell35Rect.size), resizing: .stretch, color: c0, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c10, mode: mode35)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 36 Drawing
        let cell36Rect = NSRect(x: 178, y: 226, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell36Rect.clip()
        context.translateBy(x: cell36Rect.minX, y: cell36Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell36Rect.size), resizing: .stretch, color: c7, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c10, mode: mode36)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 37 Drawing
        let cell37Rect = NSRect(x: 290, y: 226, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell37Rect.clip()
        context.translateBy(x: cell37Rect.minX, y: cell37Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell37Rect.size), resizing: .stretch, color: c2, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c10, mode: mode37)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 38 Drawing
        let cell38Rect = NSRect(x: 402, y: 226, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell38Rect.clip()
        context.translateBy(x: cell38Rect.minX, y: cell38Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell38Rect.size), resizing: .stretch, color: c9, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c10, mode: mode38)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 39 Drawing
        let cell39Rect = NSRect(x: 514, y: 226, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell39Rect.clip()
        context.translateBy(x: cell39Rect.minX, y: cell39Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell39Rect.size), resizing: .stretch, color: c4, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c10, mode: mode39)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 40 Drawing
        let cell40Rect = NSRect(x: 626, y: 226, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell40Rect.clip()
        context.translateBy(x: cell40Rect.minX, y: cell40Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell40Rect.size), resizing: .stretch, color: c11, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c10, mode: mode40)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 41 Drawing
        let cell41Rect = NSRect(x: 738, y: 226, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell41Rect.clip()
        context.translateBy(x: cell41Rect.minX, y: cell41Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell41Rect.size), resizing: .stretch, color: c6, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c10, mode: mode41)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 42 Drawing
        let cell42Rect = NSRect(x: 850, y: 226, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell42Rect.clip()
        context.translateBy(x: cell42Rect.minX, y: cell42Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell42Rect.size), resizing: .stretch, color: c1, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c10, mode: mode42)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 43 Drawing
        let cell43Rect = NSRect(x: 10, y: 128, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell43Rect.clip()
        context.translateBy(x: cell43Rect.minX, y: cell43Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell43Rect.size), resizing: .stretch, color: c0, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c6, mode: mode43)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 44 Drawing
        let cell44Rect = NSRect(x: 122, y: 128, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell44Rect.clip()
        context.translateBy(x: cell44Rect.minX, y: cell44Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell44Rect.size), resizing: .stretch, color: c7, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c6, mode: mode44)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 45 Drawing
        let cell45Rect = NSRect(x: 234, y: 128, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell45Rect.clip()
        context.translateBy(x: cell45Rect.minX, y: cell45Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell45Rect.size), resizing: .stretch, color: c2, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c6, mode: mode45)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 46 Drawing
        let cell46Rect = NSRect(x: 346, y: 128, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell46Rect.clip()
        context.translateBy(x: cell46Rect.minX, y: cell46Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell46Rect.size), resizing: .stretch, color: c9, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c6, mode: mode46)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 47 Drawing
        let cell47Rect = NSRect(x: 458, y: 128, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell47Rect.clip()
        context.translateBy(x: cell47Rect.minX, y: cell47Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell47Rect.size), resizing: .stretch, color: c4, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c6, mode: mode47)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 48 Drawing
        let cell48Rect = NSRect(x: 570, y: 128, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell48Rect.clip()
        context.translateBy(x: cell48Rect.minX, y: cell48Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell48Rect.size), resizing: .stretch, color: c11, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c6, mode: mode48)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 49 Drawing
        let cell49Rect = NSRect(x: 682, y: 128, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell49Rect.clip()
        context.translateBy(x: cell49Rect.minX, y: cell49Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell49Rect.size), resizing: .stretch, color: c6, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c6, mode: mode49)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 50 Drawing
        let cell50Rect = NSRect(x: 794, y: 128, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell50Rect.clip()
        context.translateBy(x: cell50Rect.minX, y: cell50Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell50Rect.size), resizing: .stretch, color: c1, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c6, mode: mode50)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 51 Drawing
        let cell51Rect = NSRect(x: 906, y: 128, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell51Rect.clip()
        context.translateBy(x: cell51Rect.minX, y: cell51Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell51Rect.size), resizing: .stretch, color: c8, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c6, mode: mode51)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 52 Drawing
        let cell52Rect = NSRect(x: 66, y: 30, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell52Rect.clip()
        context.translateBy(x: cell52Rect.minX, y: cell52Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell52Rect.size), resizing: .stretch, color: c0, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c9, mode: mode52)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 53 Drawing
        let cell53Rect = NSRect(x: 178, y: 30, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell53Rect.clip()
        context.translateBy(x: cell53Rect.minX, y: cell53Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell53Rect.size), resizing: .stretch, color: c7, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c9, mode: mode53)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 54 Drawing
        let cell54Rect = NSRect(x: 290, y: 30, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell54Rect.clip()
        context.translateBy(x: cell54Rect.minX, y: cell54Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell54Rect.size), resizing: .stretch, color: c2, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c9, mode: mode54)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 55 Drawing
        let cell55Rect = NSRect(x: 402, y: 30, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell55Rect.clip()
        context.translateBy(x: cell55Rect.minX, y: cell55Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell55Rect.size), resizing: .stretch, color: c9, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c9, mode: mode55)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 56 Drawing
        let cell56Rect = NSRect(x: 514, y: 30, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell56Rect.clip()
        context.translateBy(x: cell56Rect.minX, y: cell56Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell56Rect.size), resizing: .stretch, color: c4, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c9, mode: mode56)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 57 Drawing
        let cell57Rect = NSRect(x: 626, y: 30, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell57Rect.clip()
        context.translateBy(x: cell57Rect.minX, y: cell57Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell57Rect.size), resizing: .stretch, color: c11, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c9, mode: mode57)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 58 Drawing
        let cell58Rect = NSRect(x: 738, y: 30, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell58Rect.clip()
        context.translateBy(x: cell58Rect.minX, y: cell58Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell58Rect.size), resizing: .stretch, color: c6, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c9, mode: mode58)
        NSGraphicsContext.restoreGraphicsState()


        //// Cell 59 Drawing
        let cell59Rect = NSRect(x: 850, y: 30, width: 108, height: 125)
        NSGraphicsContext.saveGraphicsState()
        cell59Rect.clip()
        context.translateBy(x: cell59Rect.minX, y: cell59Rect.minY)

        TriMode59cellTonnetzMac.drawCellSym(frame: CGRect(origin: .zero, size: cell59Rect.size), resizing: .stretch, color: c1, colorOS: colorOS, pcOS: pcOSadjusted, rowOS: c9, mode: mode59)
        NSGraphicsContext.restoreGraphicsState()




        //// Symbol Drawing
        let symbolRect = NSRect(x: 453, y: 327, width: 119, height: 119)
        NSGraphicsContext.saveGraphicsState()
        symbolRect.clip()
        context.translateBy(x: symbolRect.minX, y: symbolRect.minY)

        TriMode59cellTonnetzMac.drawSharpOutline(frame: CGRect(origin: .zero, size: symbolRect.size), resizing: .stretch)
        NSGraphicsContext.restoreGraphicsState()
    }

    @objc dynamic public class func drawOuterRing(frame targetFrame: NSRect = NSRect(x: 0, y: 0, width: 118, height: 122), resizing: ResizingBehavior = .aspectFit) {
        //// General Declarations
        let context = NSGraphicsContext.current!.cgContext
        
        //// Resize to Target Frame
        NSGraphicsContext.saveGraphicsState()
        let resizedFrame: NSRect = resizing.apply(rect: NSRect(x: 0, y: 0, width: 118, height: 122), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 118, y: resizedFrame.height / 122)
        let resizedShadowScale: CGFloat = min(resizedFrame.width / 118, resizedFrame.height / 122)


        //// Color Declarations
        let shadowColor = NSColor(red: 0.293, green: 0.328, blue: 0.38, alpha: 1)

        //// Shadow Declarations
        let shadow = NSShadow()
        shadow.shadowColor = shadowColor.withAlphaComponent(0.73 * shadowColor.alphaComponent)
        shadow.shadowOffset = NSSize(width: 1, height: -1)
        shadow.shadowBlurRadius = 4.5

        //// outline Drawing
        let outlinePath = NSBezierPath()
        outlinePath.move(to: NSPoint(x: 57, y: 109.25))
        outlinePath.line(to: NSPoint(x: 102.03, y: 83.25))
        outlinePath.line(to: NSPoint(x: 102.03, y: 31.25))
        outlinePath.line(to: NSPoint(x: 57, y: 5.25))
        outlinePath.line(to: NSPoint(x: 11.97, y: 31.25))
        outlinePath.line(to: NSPoint(x: 11.97, y: 83.25))
        outlinePath.close()
        NSGraphicsContext.saveGraphicsState()
        context.setShadow(offset: NSSize(width: shadow.shadowOffset.width * resizedShadowScale, height: shadow.shadowOffset.height * resizedShadowScale), blur: shadow.shadowBlurRadius * resizedShadowScale, color: shadow.shadowColor!.cgColor)
        NSColor.black.setStroke()
        outlinePath.lineWidth = 2
        outlinePath.lineCapStyle = .round
        outlinePath.lineJoinStyle = .round
        outlinePath.stroke()
        NSGraphicsContext.restoreGraphicsState()
        
        NSGraphicsContext.restoreGraphicsState()

    }

    @objc dynamic public class func drawHexagonOutline(frame targetFrame: NSRect = NSRect(x: 0, y: 0, width: 130, height: 138), resizing: ResizingBehavior = .aspectFit) {
        //// General Declarations
        let context = NSGraphicsContext.current!.cgContext
        
        //// Resize to Target Frame
        NSGraphicsContext.saveGraphicsState()
        let resizedFrame: NSRect = resizing.apply(rect: NSRect(x: 0, y: 0, width: 130, height: 138), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 130, y: resizedFrame.height / 138)


        //// hexagon Drawing
        let hexagonPath = NSBezierPath()
        hexagonPath.move(to: NSPoint(x: 65.5, y: 133))
        hexagonPath.line(to: NSPoint(x: 120.93, y: 101))
        hexagonPath.line(to: NSPoint(x: 120.93, y: 37))
        hexagonPath.line(to: NSPoint(x: 65.5, y: 5))
        hexagonPath.line(to: NSPoint(x: 10.07, y: 37))
        hexagonPath.line(to: NSPoint(x: 10.07, y: 101))
        hexagonPath.close()
        NSColor.black.setStroke()
        hexagonPath.lineWidth = 4.5
        hexagonPath.stroke()
        
        NSGraphicsContext.restoreGraphicsState()

    }

    @objc dynamic public class func drawResizableHexagonOutline(frame targetFrame: NSRect = NSRect(x: 0, y: 0, width: 149, height: 150), resizing: ResizingBehavior = .aspectFit) {
        //// General Declarations
        let context = NSGraphicsContext.current!.cgContext
        
        //// Resize to Target Frame
        NSGraphicsContext.saveGraphicsState()
        let resizedFrame: NSRect = resizing.apply(rect: NSRect(x: 0, y: 0, width: 149, height: 150), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 149, y: resizedFrame.height / 150)


        //// Symbol Drawing
        let symbolRect = NSRect(x: 9, y: 6, width: 130, height: 138)
        NSGraphicsContext.saveGraphicsState()
        symbolRect.clip()
        context.translateBy(x: symbolRect.minX, y: symbolRect.minY)

        TriMode59cellTonnetzMac.drawHexagonOutline(frame: CGRect(origin: .zero, size: symbolRect.size), resizing: .stretch)
        NSGraphicsContext.restoreGraphicsState()
        
        NSGraphicsContext.restoreGraphicsState()

    }

    @objc dynamic public class func drawSharpOutline(frame targetFrame: NSRect = NSRect(x: 0, y: 0, width: 125, height: 125), resizing: ResizingBehavior = .aspectFit) {
        //// General Declarations
        let context = NSGraphicsContext.current!.cgContext
        
        //// Resize to Target Frame
        NSGraphicsContext.saveGraphicsState()
        let resizedFrame: NSRect = resizing.apply(rect: NSRect(x: 0, y: 0, width: 125, height: 125), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 125, y: resizedFrame.height / 125)


        //// Color Declarations
        let color5 = NSColor(red: 0.404, green: 0.404, blue: 0.404, alpha: 1)

        //// Bezier Drawing
        NSGraphicsContext.saveGraphicsState()
        context.setAlpha(0.7)
        context.beginTransparencyLayer(auxiliaryInfo: nil)

        let bezierPath = NSBezierPath()
        bezierPath.move(to: NSPoint(x: 61.74, y: 115))
        bezierPath.curve(to: NSPoint(x: 32.74, y: 98), controlPoint1: NSPoint(x: 61.74, y: 115), controlPoint2: NSPoint(x: 45.85, y: 105.57))
        bezierPath.curve(to: NSPoint(x: 16.74, y: 89), controlPoint1: NSPoint(x: 24.06, y: 92.99), controlPoint2: NSPoint(x: 16.74, y: 89))
        bezierPath.line(to: NSPoint(x: 16.74, y: 36))
        bezierPath.line(to: NSPoint(x: 61.74, y: 10))
        bezierPath.line(to: NSPoint(x: 107.74, y: 36))
        bezierPath.line(to: NSPoint(x: 107.74, y: 89))
        bezierPath.line(to: NSPoint(x: 61.74, y: 115))
        bezierPath.close()
        bezierPath.move(to: NSPoint(x: 61.74, y: 124))
        bezierPath.curve(to: NSPoint(x: 115.74, y: 93), controlPoint1: NSPoint(x: 61.74, y: 124), controlPoint2: NSPoint(x: 115.74, y: 93))
        bezierPath.line(to: NSPoint(x: 115.74, y: 32))
        bezierPath.line(to: NSPoint(x: 61.74, y: 1))
        bezierPath.line(to: NSPoint(x: 8.74, y: 32))
        bezierPath.line(to: NSPoint(x: 8.74, y: 93))
        bezierPath.curve(to: NSPoint(x: 26.74, y: 103), controlPoint1: NSPoint(x: 8.74, y: 93), controlPoint2: NSPoint(x: 17.04, y: 97.4))
        bezierPath.curve(to: NSPoint(x: 61.74, y: 124), controlPoint1: NSPoint(x: 42.25, y: 111.96), controlPoint2: NSPoint(x: 61.74, y: 124))
        bezierPath.line(to: NSPoint(x: 61.74, y: 124))
        bezierPath.close()
        NSColor.white.setFill()
        bezierPath.fill()
        color5.setStroke()
        bezierPath.lineWidth = 4.5
        bezierPath.lineCapStyle = .round
        bezierPath.lineJoinStyle = .bevel
        bezierPath.stroke()

        context.endTransparencyLayer()
        NSGraphicsContext.restoreGraphicsState()
        
        NSGraphicsContext.restoreGraphicsState()

    }




    @objc(TriMode59cellTonnetzMacResizingBehavior)
    public enum ResizingBehavior: Int {
        case aspectFit /// The content is proportionally resized to fit into the target rectangle.
        case aspectFill /// The content is proportionally resized to completely fill the target rectangle.
        case stretch /// The content is stretched to match the entire target rectangle.
        case center /// The content is centered in the target rectangle, but it is NOT resized.

        public func apply(rect: NSRect, target: NSRect) -> NSRect {
            if rect == target || target == NSRect.zero {
                return rect
            }

            var scales = NSSize.zero
            scales.width = abs(target.width / rect.width)
            scales.height = abs(target.height / rect.height)

            switch self {
                case .aspectFit:
                    scales.width = min(scales.width, scales.height)
                    scales.height = scales.width
                case .aspectFill:
                    scales.width = max(scales.width, scales.height)
                    scales.height = scales.width
                case .stretch:
                    break
                case .center:
                    scales.width = 1
                    scales.height = 1
            }

            var result = rect.standardized
            result.size.width *= scales.width
            result.size.height *= scales.height
            result.origin.x = target.minX + (target.width - result.width) / 2
            result.origin.y = target.minY + (target.height - result.height) / 2
            return result
        }
    }
}
